# GitHub Actions Workflow: Run Tests
#
# This workflow is triggered on pushes and pull requests to the 'main' branch.
# It performs the following steps:
#   1. Checks out the repository code.
#   2. Sets up Python 3.12.
#   3. Upgrades pip.
#   4. Runs all unit tests in files matching 'test_*.py' using unittest.
#
# Usage:
# - Ensures that all code changes are tested automatically.
# - Helps maintain code quality by running tests on every commit and PR to 'main'.
# - To add more dependencies, update the 'Install Dependencies' step.
# - To change the Python version, modify the 'python-version' field.
#
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
